"""initial_schema

Revision ID: d6ff3e007afc
Revises: 
Create Date: 2026-03-28 19:04:52.605260

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6ff3e007afc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('topic_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('has_accepted_answer', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('scrape_status', sa.Text(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topics_category_id', 'topics', ['category_id'], unique=False)
    op.create_index('ix_topics_created_at', 'topics', ['created_at'], unique=False)
    op.create_index('ix_topics_scrape_status', 'topics', ['scrape_status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('post_number', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cooked_html', sa.Text(), nullable=True),
    sa.Column('reply_to_post_number', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reads', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accepted_answer', sa.Boolean(), nullable=False),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at_server', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_embedded'), 'posts', ['embedded'], unique=False)
    op.create_index('ix_posts_topic_id', 'posts', ['topic_id'], unique=False)
    op.create_index('ix_posts_username', 'posts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_username', table_name='posts')
    op.drop_index('ix_posts_topic_id', table_name='posts')
    op.drop_index(op.f('ix_posts_embedded'), table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_topics_scrape_status', table_name='topics')
    op.drop_index('ix_topics_created_at', table_name='topics')
    op.drop_index('ix_topics_category_id', table_name='topics')
    op.drop_table('topics')
    op.drop_table('categories')
    # ### end Alembic commands ###
